spring.datasource.url=jdbc:mariadb://192.168.15.26:3306/crud
spring.datasource.username=root
spring.datasource.password=Better@40
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update